openapi: 3.0.0

info:
  contact:
    name: Stefano Rivoir
    email: rs4000@gmail.com
  title: Passweaver API
  version: v1
  description: Passweaver API documentation
  license:
    name: MIT
    url: https://mit-license.org/

servers:
  - url: http://yourserver

tags:
  - name: "Authentication"
    description: Login
  - name: "Users"
    description: Operations on users
  - name: "Groups"
    description: Operations on user groups
  - name: "Folders"
    description: Operations on folders
  - name: "Folder permissions"
    description: Folder permissions
  - name: "Items"
    description: Items
  - name: "Events"
    description: Events
  - name: "Utilities"
    description: Utilities

paths:
  /login:
    $ref: '.\paths\login.yaml'
  /users:
    $ref: '.\paths\users.yaml'
  /users/{userid}:
    $ref: '.\paths\usersid.yaml'
  /users/personalunlock:
    $ref: '.\paths\userspersonalunlock.yaml'
  /groups/{parentgroupid}/groups:
    $ref: '.\paths\groupsidgroups.yaml'
  /groups/{groupid}:
    $ref: '.\paths\groupsid.yaml'
  /folders/{parentfolderid}/folders:
    $ref: '.\paths\foldersidfolders.yaml'
  /folders/{folderid}:
    $ref: '.\paths\foldersid.yaml'
  /folders/{folderid}/groups:
    $ref: '.\paths\foldersidgroups.yaml'
  /folders/{folderid}/groups/{groupid}:
    $ref: '.\paths\foldersgroupsid.yaml'
  /folders/{folderid}/items:
    $ref: '.\paths\foldersiditems.yaml'
  /items/{itemid}:
    $ref: '.\paths\itemsid.yaml'
  /items:
    $ref: '.\paths\items.yaml'
  /util/stats:
    $ref: '.\paths\utilstats.yaml'
  /util/generatepassword:
    $ref: '.\paths\utilgeneratepassword.yaml'
  /events:
    $ref: '.\paths\events.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
