openapi: 3.0.0

info:
  contact:
    name: Stefano Rivoir
    email: rs4000@gmail.com
  title: Passweaver API
  version: v1
  description: Passweaver API documentation
  license:
    name: MIT
    url: https://mit-license.org/

servers:
  - url: http://yourserver

tags:
  - name: "Authentication"
    description: Login
  - name: "Users"
    description: Operations on users
  - name: "User settings"
    description: User settings
  - name: "Groups"
    description: Operations on user groups
  - name: "Groups members"
    description: Add and remove users from groups
  - name: "Folders"
    description: Operations on folders
  - name: "Personal folders"
    description: "Personal folders"
  - name: "Folder permissions"
    description: Folder permissions
  - name: "Items"
    description: Items
  - name: "Item types"
    description: Item types
  - name: "One time tokens"
    description: "One time tokens"
  - name: "Events"
    description: Events
  - name: "Utilities"
    description: Utilities

paths:
  /login:
    $ref: '.\paths\login.yaml'
  /users:
    $ref: '.\paths\users.yaml'
  /users/{userid}:
    $ref: '.\paths\usersid.yaml'
  /users/{userid}/settings:
    $ref: '.\paths\usersidsettings.yaml'
  /users/{userid}/activity:
    $ref: '.\paths\usersidactivity.yaml'
  /users/{userid}/folders:
    $ref: '.\paths\usersidfolders.yaml'
  /personal/unlock:
    $ref: '.\paths\personalunlock.yaml'
  /personal/password:
    $ref: '.\paths\personalpassword.yaml'
  /groups/{parentgroupid}/groups:
    $ref: '.\paths\groupsidgroups.yaml'
  /groups/{groupid}:
    $ref: '.\paths\groupsid.yaml'
  /groups/{groupid}/users/{userid}:
    $ref: '.\paths\groupsidusersid.yaml'
  /groups/{groupid}/users:
    $ref: '.\paths\groupsidusers.yaml'
  /groups/tree:
    $ref: '.\paths\groupstree.yaml'
  /groups:
    $ref: '.\paths\groups.yaml'
  /folders/{parentfolderid}/folders:
    $ref: '.\paths\foldersidfolders.yaml'
  /folders/{folderid}:
    $ref: '.\paths\foldersid.yaml'
  /folders/{folderid}/groups/{groupid}:
    $ref: '.\paths\foldersidgroupsid.yaml'
  /folders/{folderid}/groups:
    $ref: '.\paths\foldersidgroups.yaml'
  /folders/{folderid}/items:
    $ref: '.\paths\foldersiditems.yaml'
  /folders/tree:
    $ref: '.\paths\folderstree.yaml'
  /items/{itemid}:
    $ref: '.\paths\itemsid.yaml'
  /items/{itemid}/activity:
    $ref: '.\paths\itemsidactivity.yaml'
  /items:
    $ref: '.\paths\items.yaml'
  /itemtypes:
    $ref: '.\paths\itemtypes.yaml'
  /itemtypes/{itemtypeid}:
    $ref: '.\paths\itemtypesid.yaml'
  /util/info:
    $ref: '.\paths\utilinfo.yaml'
  /util/generatepassword:
    $ref: '.\paths\utilgeneratepassword.yaml'
  /util/clearcache:
    $ref: '.\paths\utilclearcache.yaml'
  /events:
    $ref: '.\paths\events.yaml'
  /onetimetokens:
    $ref: '.\paths\onetimetokens.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
