require("./common.cjs")

require("./login.spec.cjs")
require("./itemtypes.spec.cjs")
require("./users.spec.cjs")
require("./usersettings.spec.cjs")
require("./onetimetokens.spec.cjs")
require("./items.spec.cjs")
require("./folderspermissions.cjs")
require("./util.spec.cjs")
require("./generator.spec.cjs")