changelog:
  categories:
    - title: New features 🎉
      labels:
        - enhancement
    - title: Bugs fixed 🐛
      labels:
        - bug
    - title: Performance improvements
      labels:
        - performance
    - title: Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"