# Success response
status:
  type: string
  enum: [ "success", "failed" ]

statussuccess:
  type: string
  enum: [ "success" ]

statusfailed:
  type: string
  enum: [ "failed" ]

success:
  description: dummy
  content:
    application/json:
      schema:
        type: object
        properties:
          status:
            $ref: '#/statussuccess'
          data:
            type: object

unprocessable:
  description: Object cannot be processed
  content:
    application/json:
      schema:
        type: object
        properties:
          success:
            $ref: '#/statusfailed'
          message:
            type: string
            example: Error message
          data:
            type: object
            example: {}

badrequest:
  description: Payload data is not readable, or missing some elements
  content:
    application/json:
      schema:
        type: object
        properties:
          success:
            $ref: '#/statusfailed'
          message:
            type: string
            example: Bad request
          data:
            type: object
            example: {}

forbidden:
  description: You don't have permissions for the operation
  content:
    application/json:
      schema:
        type: object
        properties:
          success:
            $ref: '#/statusfailed'
          message:
            type: string
            example: No permissions
          data:
            type: object
            example: {}

unauthorized:
  description: Your are not logged in
  content:
    application/json:
      schema:
        type: object
        properties:
          success:
            $ref: '#/statusfailed'
          message:
            type: string
            example: Unauthorized
          data:
            type: object
            example: {}

created:
  description: dummy
  content:
    application/json:
      schema:
        type: object
        properties:
          status:
            $ref: '#/statussuccess'
          data:
            type: object
            properties:
              id:
                type: string
                description: ID of new object

notfound:
  description: Not found
  content:
    application/json:
      schema:
        type: object
        properties:
          status:
            $ref: '#/statusfailed'
          message:
            type: string
            description: Error message
            example: Not found
          data:
            type: object